#pragma once

#include <ymir/utils/StringEnum.hh>
#include <vector>
#include <string>
#include <set>

namespace global {

    DECLARE_ENUM_HEADER (CoreNames, std::string,
			 ARRAY_ALLOC,
			 ARRAY_MODULE,
			 ASSERT_FUNC,
			 BEGIN_OP_OVERRIDE,
			 BINARY_OP_OVERRIDE,
			 BINARY_OP_OVERRIDE_RIGHT,
			 CLASS_ALLOC,
			 CONTAIN_OP_OVERRIDE,
			 CORE_MODULE,			 
			 DCOPY_OP_OVERRIDE,
			 DCOPY_TRAITS,
			 DEBUG_VERSION,
			 DOLLAR_OP_OVERRIDE,
			 DUPLICATION_MODULE,
			 DUPL_ANY,
			 DUPL_SLICE,
			 END_OP_OVERRIDE,
			 EQUALS_OP_OVERRIDE,
			 EXCEPTION_MODULE,
			 EXCEPTION_RETHROW_FUNC,
			 EXCEPTION_TYPE,
			 EXCEPT_GET_VALUE,
			 EXCEPT_POP,
			 EXCEPT_PUSH,
			 GET_OP_OVERRIDE,
			 INDEX_ASSIGN_OP_OVERRIDE,
			 INDEX_OP_OVERRIDE,
			 JMP_BUF_TYPE,
			 LOGICAL_OP_OVERRIDE,
			 NEXT_OP_OVERRIDE,
			 OBJECT_MODULE,
			 OBJECT_TYPE,
			 OUT_OF_ARRAY,
			 OUT_OF_ARRAY_TYPE,
			 RETHROW,
			 RUN_MAIN,
			 RUN_MAIN_DEBUG,
			 SEG_FAULT_TYPE,
			 SET_JMP,
			 SLICE_CONCAT,
			 THROW,
			 TYPE_IDS,
			 TYPE_INFO,
			 TYPE_INFO_EQUAL,
			 TYPE_INFO_MODULE,
			 UNARY_ASSIGN_OP_OVERRIDE,
			 UNARY_OP_OVERRIDE,
    );
    
}
