#pragma once


#include "ArrayInfo.hh"
#include "InfoType.hh"
#include "BoolInfo.hh"
#include "EnumInfo.hh"
#include "CharInfo.hh"
#include "FixedInfo.hh"
#include "FloatInfo.hh"
#include "NullInfo.hh"
#include "FunctionInfo.hh"
#include "PtrFuncInfo.hh"
#include "PtrInfo.hh"
#include "RefInfo.hh"
#include "UndefInfo.hh"
#include "VoidInfo.hh"
#include "StringInfo.hh"
#include "RangeInfo.hh"
#include "TupleInfo.hh"
