#pragma once

#include <ymir/syntax/expression/ArrayAlloc.hh>
#include <ymir/syntax/expression/Assert.hh>
#include <ymir/syntax/expression/Binary.hh>
#include <ymir/syntax/expression/Block.hh>
#include <ymir/syntax/expression/Bool.hh>
#include <ymir/syntax/expression/Break.hh>
#include <ymir/syntax/expression/Cast.hh>
#include <ymir/syntax/expression/Catch.hh>
#include <ymir/syntax/expression/Char.hh>
#include <ymir/syntax/expression/DecoratedExpression.hh>
#include <ymir/syntax/expression/Dollar.hh>
#include <ymir/syntax/expression/Fixed.hh>
#include <ymir/syntax/expression/Float.hh>
#include <ymir/syntax/expression/For.hh>
#include <ymir/syntax/expression/FuncPtr.hh>
#include <ymir/syntax/expression/If.hh>
#include <ymir/syntax/expression/Ignore.hh>
#include <ymir/syntax/expression/Intrinsics.hh>
#include <ymir/syntax/expression/Is.hh>
#include <ymir/syntax/expression/Lambda.hh>
#include <ymir/syntax/expression/List.hh>
#include <ymir/syntax/expression/MacroCall.hh>
#include <ymir/syntax/expression/Match.hh>
#include <ymir/syntax/expression/MultOperator.hh>
#include <ymir/syntax/expression/NamedExpression.hh>
#include <ymir/syntax/expression/Null.hh>
#include <ymir/syntax/expression/OfVar.hh>
#include <ymir/syntax/expression/Pragma.hh>
#include <ymir/syntax/expression/Return.hh>
#include <ymir/syntax/expression/Scope.hh>
#include <ymir/syntax/expression/Set.hh>
#include <ymir/syntax/expression/String.hh>
#include <ymir/syntax/expression/Template.hh>
#include <ymir/syntax/expression/TemplateChecker.hh>
#include <ymir/syntax/expression/Throw.hh>
#include <ymir/syntax/expression/TupleDest.hh>
#include <ymir/syntax/expression/Unary.hh>
#include <ymir/syntax/expression/Unit.hh>
#include <ymir/syntax/expression/Var.hh>
#include <ymir/syntax/expression/VarDecl.hh>
#include <ymir/syntax/expression/DestructDecl.hh>
#include <ymir/syntax/expression/VariadicVar.hh>
#include <ymir/syntax/expression/While.hh>
