#pragma once

#include <ymir/semantic/generator/value/Affect.hh>
#include <ymir/semantic/generator/value/ArrayValue.hh>
#include <ymir/semantic/generator/value/Binary.hh>
#include <ymir/semantic/generator/value/BinaryBool.hh>
#include <ymir/semantic/generator/value/BinaryFloat.hh>
#include <ymir/semantic/generator/value/BinaryInt.hh>
#include <ymir/semantic/generator/value/Block.hh>
#include <ymir/semantic/generator/value/BoolValue.hh>
#include <ymir/semantic/generator/value/CharValue.hh>
#include <ymir/semantic/generator/value/Conditional.hh>
#include <ymir/semantic/generator/value/Copier.hh>
#include <ymir/semantic/generator/value/Fixed.hh>
#include <ymir/semantic/generator/value/FloatValue.hh>
#include <ymir/semantic/generator/value/None.hh>
#include <ymir/semantic/generator/value/ParamVar.hh>
#include <ymir/semantic/generator/value/Referencer.hh>
#include <ymir/semantic/generator/value/Set.hh>
#include <ymir/semantic/generator/value/VarDecl.hh>
#include <ymir/semantic/generator/value/VarRef.hh>
