#pragma once

#include <ymir/semantic/generator/value/Affect.hh>
#include <ymir/semantic/generator/value/Aliaser.hh>
#include <ymir/semantic/generator/value/ArrayAccess.hh>
#include <ymir/semantic/generator/value/ArrayValue.hh>
#include <ymir/semantic/generator/value/Binary.hh>
#include <ymir/semantic/generator/value/BinaryBool.hh>
#include <ymir/semantic/generator/value/BinaryFloat.hh>
#include <ymir/semantic/generator/value/BinaryInt.hh>
#include <ymir/semantic/generator/value/Block.hh>
#include <ymir/semantic/generator/value/BoolValue.hh>
#include <ymir/semantic/generator/value/Break.hh>
#include <ymir/semantic/generator/value/Call.hh>
#include <ymir/semantic/generator/value/CharValue.hh>
#include <ymir/semantic/generator/value/Conditional.hh>
#include <ymir/semantic/generator/value/Copier.hh>
#include <ymir/semantic/generator/value/Fixed.hh>
#include <ymir/semantic/generator/value/FloatValue.hh>
#include <ymir/semantic/generator/value/FrameProto.hh>
#include <ymir/semantic/generator/value/Loop.hh>
#include <ymir/semantic/generator/value/ModuleAccess.hh>
#include <ymir/semantic/generator/value/MultSym.hh>
#include <ymir/semantic/generator/value/NamedGenerator.hh>
#include <ymir/semantic/generator/value/None.hh>
#include <ymir/semantic/generator/value/ParamVar.hh>
#include <ymir/semantic/generator/value/ProtoVar.hh>
#include <ymir/semantic/generator/value/Referencer.hh>
#include <ymir/semantic/generator/value/Set.hh>
#include <ymir/semantic/generator/value/SliceAccess.hh>
#include <ymir/semantic/generator/value/Struct.hh>
#include <ymir/semantic/generator/value/StructAccess.hh>
#include <ymir/semantic/generator/value/StructCst.hh>
#include <ymir/semantic/generator/value/TupleAccess.hh>
#include <ymir/semantic/generator/value/TupleValue.hh>
#include <ymir/semantic/generator/value/Unary.hh>
#include <ymir/semantic/generator/value/UnaryBool.hh>
#include <ymir/semantic/generator/value/UnaryFloat.hh>
#include <ymir/semantic/generator/value/UnaryInt.hh>
#include <ymir/semantic/generator/value/VarDecl.hh>
#include <ymir/semantic/generator/value/VarRef.hh>
