#pragma once

#include <ymir/semantic/generator/value/Atomic.hh>
#include <ymir/semantic/generator/value/Addresser.hh>
#include <ymir/semantic/generator/value/Affect.hh>
#include <ymir/semantic/generator/value/Aliaser.hh>
#include <ymir/semantic/generator/value/ArrayAccess.hh>
#include <ymir/semantic/generator/value/ArrayAlloc.hh>
#include <ymir/semantic/generator/value/ArrayValue.hh>
#include <ymir/semantic/generator/value/Binary.hh>
#include <ymir/semantic/generator/value/BinaryBool.hh>
#include <ymir/semantic/generator/value/BinaryChar.hh>
#include <ymir/semantic/generator/value/BinaryFloat.hh>
#include <ymir/semantic/generator/value/BinaryInt.hh>
#include <ymir/semantic/generator/value/BinaryPtr.hh>
#include <ymir/semantic/generator/value/Block.hh>
#include <ymir/semantic/generator/value/BoolValue.hh>
#include <ymir/semantic/generator/value/Break.hh>
#include <ymir/semantic/generator/value/Call.hh>
#include <ymir/semantic/generator/value/Cast.hh>
#include <ymir/semantic/generator/value/CharValue.hh>
#include <ymir/semantic/generator/value/Class.hh>
#include <ymir/semantic/generator/value/ClassCst.hh>
#include <ymir/semantic/generator/value/Conditional.hh>
#include <ymir/semantic/generator/value/ConstructorProto.hh>
#include <ymir/semantic/generator/value/Copier.hh>
#include <ymir/semantic/generator/value/DelegateValue.hh>
#include <ymir/semantic/generator/value/Enum.hh>
#include <ymir/semantic/generator/value/ExitScope.hh>
#include <ymir/semantic/generator/value/FakeValue.hh>
#include <ymir/semantic/generator/value/FieldOffset.hh>
#include <ymir/semantic/generator/value/Fixed.hh>
#include <ymir/semantic/generator/value/FloatValue.hh>
#include <ymir/semantic/generator/value/FrameProto.hh>
#include <ymir/semantic/generator/value/GlobalConstant.hh>
#include <ymir/semantic/generator/value/LambdaProto.hh>
#include <ymir/semantic/generator/value/List.hh>
#include <ymir/semantic/generator/value/Loop.hh>
#include <ymir/semantic/generator/value/MacroRef.hh>
#include <ymir/semantic/generator/value/MacroRuleRef.hh>
#include <ymir/semantic/generator/value/MethodProto.hh>
#include <ymir/semantic/generator/value/MethodTemplateRef.hh>
#include <ymir/semantic/generator/value/ModuleAccess.hh>
#include <ymir/semantic/generator/value/MultSym.hh>
#include <ymir/semantic/generator/value/NamedGenerator.hh>
#include <ymir/semantic/generator/value/None.hh>
#include <ymir/semantic/generator/value/NullValue.hh>
#include <ymir/semantic/generator/value/OptionValue.hh>
#include <ymir/semantic/generator/value/ParamVar.hh>
#include <ymir/semantic/generator/value/ProtoVar.hh>
#include <ymir/semantic/generator/value/RangeValue.hh>
#include <ymir/semantic/generator/value/Referencer.hh>
#include <ymir/semantic/generator/value/Return.hh>
#include <ymir/semantic/generator/value/Set.hh>
#include <ymir/semantic/generator/value/SizeOf.hh>
#include <ymir/semantic/generator/value/SliceAccess.hh>
#include <ymir/semantic/generator/value/SliceConcat.hh>
#include <ymir/semantic/generator/value/SliceValue.hh>
#include <ymir/semantic/generator/value/StringValue.hh>
#include <ymir/semantic/generator/value/Struct.hh>
#include <ymir/semantic/generator/value/StructAccess.hh>
#include <ymir/semantic/generator/value/StructCst.hh>
#include <ymir/semantic/generator/value/SuccessScope.hh>
#include <ymir/semantic/generator/value/TemplateClassCst.hh>
#include <ymir/semantic/generator/value/TemplateRef.hh>
#include <ymir/semantic/generator/value/TemplateSyntaxList.hh>
#include <ymir/semantic/generator/value/TemplateSyntaxWrapper.hh>
#include <ymir/semantic/generator/value/Throw.hh>
#include <ymir/semantic/generator/value/ThrowBlock.hh>
#include <ymir/semantic/generator/value/TupleAccess.hh>
#include <ymir/semantic/generator/value/TupleValue.hh>
#include <ymir/semantic/generator/value/Unary.hh>
#include <ymir/semantic/generator/value/UnaryBool.hh>
#include <ymir/semantic/generator/value/UnaryFloat.hh>
#include <ymir/semantic/generator/value/UnaryInt.hh>
#include <ymir/semantic/generator/value/UnaryPointer.hh>
#include <ymir/semantic/generator/value/UnionCst.hh>
#include <ymir/semantic/generator/value/UniqValue.hh>
#include <ymir/semantic/generator/value/VarDecl.hh>
#include <ymir/semantic/generator/value/VarRef.hh>
#include <ymir/semantic/generator/value/VtableAccess.hh>
