#pragma once

#include <ymir/semantic/generator/value/Binary.hh>

namespace semantic {

    namespace generator {

	/**
	 * \struct Binary 
	 * Binary operations on ints
	 */
	class Loop : public Value {

	    Generator _test;

	    Generator _content;

	    bool _isDo = false;
	    
	private :

	    friend Generator;
	    
	    Loop ();

	    Loop (const lexing::Word & loc, const Generator & type, const Generator & test, const Generator & content, bool isDo);

	public :

	    /**
	     * \brief Generate a 
	     */
	    static Generator init (const lexing::Word & loc, const Generator & type, const Generator & test, const Generator & content, bool isDo);
	    
	    /** 
	     * \brief Mandatory function used inside proxy design pattern
	     */
	    Generator clone () const  override;
	    
	    /**
	     * \return is this symbol the same as other (no only address, or type)
	     */
	    bool equals (const Generator & other) const override;	    

	    /** 
	     * \return the test of the condition
	     */
	    const Generator & getTest () const;

	    /**
	     * \return the content to execute if the test if valid
	     */
	    const Generator & getContent () const;

	    /**
	     * \brief Tell if the loop was generated by a do {} while 
	     */
	    bool isDo () const;

	    std::string prettyString () const override;
	};
	
    }

}
