#include <ymir/errors/ListError.hh>

namespace Ymir {    
    DECLARE_ENUM_WITH_TYPE (ExternalError, std::string,			         
			    AFFECT_COMPILE_TIME		    = "affectation at compile time is prohibited",
			    BORROWED_HERE		    = "borrow occured here",
			    BREAK_INSIDE_EXPR		    = "break here will result in an undefined behavior",
			    BREAK_NO_LOOP		    = "break statement must be placed inside a loop",
			    COMPILATION_END		    = "",
			    COMPILE_TIME_UNKNOWN	    = "the value of this expression is required, but could not be known at compile time",
			    CONFLICT_DECORATOR		    = "conflicting decorator",
			    DECO_OUT_OF_CONTEXT		    = "decorator %(y) is unusable in this context",
			    DISCARD_CONST		    = "discard the constant qualifier is prohibited",
			    DISCARD_CONST_LEVEL		    = "discard the constant qualifier is prohibited, left operand mutability level is %(y) but must be at most %(y)",
			    DISCARD_LOCALITY		    = "discard the locality is prohibited",
			    DYNAMIC_CAST_FAILED		    = "dynamic cast failed : %",
			    IMMUTABLE_LVALUE		    = "left operand is immutable",
			    IMPLICIT_COPY		    = "implicit memory copy of type %(y) is not allowed",
			    IMPLICIT_REFERENCE		    = "implicit referencing of type %(y) is not allowed",
			    INCOMPATIBLE_TYPES		    = "incompatible types %(y) and %(y)",
			    INSERT_NO_TABLE		    = "insertion of a symbol in an entity that cannot be a referent",
			    MALFORMED_CHAR		    = "malformed literal, number of %(y) is %(y)",
			    MUTABLE_CONST_PARAM		    = "a parameter cannot be mutable, if it is not a reference",
			    MUTABLE_CONST_RETURN	    = "a return value cannot be mutable, if it is not a reference",
			    NEVER_USED			    = "symbol %(y) declared but never used",
			    NOT_A_LVALUE		    = "not a lvalue",
			    NO_ALIAS_EXIST		    = "cannot alias type %(y)",
			    NO_COPY_EXIST		    = "no copy exists for type %(y)",
			    NO_SUCH_FILE		    = "%(y) no such file, or permission denied",
			    NULL_PTR			    = "try to unref a null pointer",
			    OVERFLOW			    = "overflow capacity for type %(y) = %(y)",
			    PACKED_AND_UNION		    = "structure could not be packed and union at the same time",
			    REF_NOT_TYPE		    = "use a reference as a value",
			    REF_NO_EFFECT		    = "the creation of ref has no effect on left operand",
			    REF_NO_VALUE		    = "%(y) declared as a reference but not initialized",
			    RETURN_INSIDE_EXPR		    = "return here will result in an undefined behavior", 
			    RETURN_LOCAL_REFERENCE	    = "expression does not live long enough",
			    SHADOWING_DECL		    = "declaration of %(y) shadow another declaration",
			    SPECIALISATION_WOTK_WITH_BOTH   = "%(y) called with {%(y)} work with both",
			    STATIC_ARRAY_REF		    = "left operand is a static array, it cannot store a reference to a dynamic array",
			    SYNTAX_ERROR_AT		    = "[%] expected, when %(y) found",	// syntax error a specific location
			    SYNTAX_ERROR_AT_SIMPLE	    = "%(y) unexpected",	// syntax error a specific location
			    SYNTAX_ERROR_IF_ON_NON_TEMPLATE = "test on non template declaration",
			    SYNTAX_ERROR_MISSING_TEMPL_PAR  = "multiple ! arguments are not allowed",
			    UNDEFINED_BIN_OP		    = "undefined operator %(y) for types %(y) and %(y)",
			    UNDEFINED_BRACKETS_OP	    = "index operator is not defined for type %(y) and {%(y)}",
			    UNDEFINED_CA		    = "custom attribute %(y), does not exist in this context",
			    UNDEFINED_CALL_OP		    = "call operator is not defined for type %(y) and {%(y)}",
			    UNDEFINED_ESCAPE		    = "undefined escape sequence",
			    UNDEFINED_UN_OP		    = "undefined operator %(y) for type %(y)",
			    UNDEFINED_SUB_PART              = "undefined sub symbol %(y)",
			    UNDEFINED_SUB_PART_FOR              = "undefined sub symbol %(y) for module %(y)",
			    UNDEF_TYPE			    = "undefined type %(y)",
			    UNDEF_VAR			    = "undefined symbol %(y)",
			    UNREACHBLE_STATEMENT	    = "unreachable statement",
			    UNTERMINATED_SEQUENCE	    = "unterminated escape sequence",
			    USELESS_DECORATOR		    = "useless decorator",
			    USE_AS_TYPE			    = "expression used as type",
			    VAR_DECL_WITH_NOTHING	    = "var declaration must at least have a type or a value",
			    VOID_VAR			    = "cannot declare var of type void",
			    WRONG_MODULE_NAME		    = "module named %(y) must be placed in file named %(y)",			    
			    FORWARD_REFERENCE_VAR           = "the type cannot be infered, as it depends on a forward reference"
    );    
}
