#include <ymir/errors/ListError.hh>

namespace Ymir {    
    DECLARE_ENUM_WITH_TYPE (ExternalError, std::string,			         
			    SYNTAX_ERROR_AT = "[%] expected, when %(y) found", // syntax error a specific location
			    SYNTAX_ERROR_AT_SIMPLE = "%(y) unexpected", // syntax error a specific location
			    SYNTAX_ERROR_MISSING_TEMPL_PAR = "multiple ! arguments are not allowed",
			    SYNTAX_ERROR_IF_ON_NON_TEMPLATE = "test on non template declaration",
			    NO_SUCH_FILE = "%(y) no such file, or permission denied",
			    COMPILATION_END = "",
			    DYNAMIC_CAST_FAILED = "dynamic cast failed : %",
			    NULL_PTR = "try to unref a null pointer",
			    INSERT_NO_TABLE = "insertion of a symbol in an entity that cannot be a referent",
			    WRONG_MODULE_NAME = "module named %(y) must be placed in file named %(y)",
			    SHADOWING_DECL = "declaration of %(y) shadow another declaration",
			    UNDEFINED_CA = "custom attribute %(y), does not exist in this context",
			    PACKED_AND_UNION = "structure could not be packed and union at the same time",
			    VAR_DECL_WITH_NOTHING = "var declaration must at least have a type or a value",
			    INCOMPATIBLE_TYPES = "incompatible types %(y) and %(y)",
			    UNDEF_TYPE = "undefined type %(y)",
			    UNREACHBLE_STATEMENT = "unreachable statement",
			    OVERFLOW = "overflow capacity for type %(y)",
			    UNDEFINED_BIN_OP = "undefined operator %(y) for types %(y) and %(y)",
			    UNDEF_VAR = "undefined symbol %(y)",
			    NEVER_USED = "symbol %(y) declared but never used",
			    VOID_VAR = "cannot declare var of type void",
			    NOT_A_LVALUE = "not a lvalue",
			    UNDEFINED_ESCAPE = "undefined escape sequence",
			    UNTERMINATED_SEQUENCE = "unterminated escape sequence",
			    MALFORMED_CHAR = "malformed literal, number of %(y) is %(y)",
			    IMPLICIT_REFERENCE = "implicit referencing of type %(y) is not allowed",
			    IMPLICIT_COPY = "implicit memory copy of type %(y) is not allowed",
			    IMMUTABLE_LVALUE = "left operand is immutable",
			    DISCARD_CONST = "discard the constant qualifier is prohibited",
			    USELESS_DECORATOR = "useless decorator",
			    DECO_OUT_OF_CONTEXT = "decorator %(y) is unusable in this context",
			    MUTABLE_CONST_PARAM = "a parameter cannot be mutable, if it is not a reference",
			    MUTABLE_CONST_RETURN = "a return value cannot be mutable, if it is not a reference",
			    RETURN_LOCAL_REFERENCE = "expression does not live long enough",
			    BORROWED_HERE = "borrow occured here",
			    CONFLICT_DECORATOR = "conflicting decorator",
			    REF_NO_VALUE = "%(y) declared as a reference but not initialized",
			    STATIC_ARRAY_REF = "left operand is a static array, it cannot store a reference to a dynamic array",
			    NO_COPY_EXIST = "no copy exists for type %(y)",
			    REF_NOT_TYPE = "use a reference as a value",
			    USE_AS_TYPE = "expression used as type"
    );    
}
