#pragma once

#include <ymir/semantic/generator/type/Array.hh>
#include <ymir/semantic/generator/type/Bool.hh>
#include <ymir/semantic/generator/type/Char.hh>
#include <ymir/semantic/generator/type/ClassRef.hh>
#include <ymir/semantic/generator/type/Closure.hh>
#include <ymir/semantic/generator/type/Delegate.hh>
#include <ymir/semantic/generator/type/Float.hh>
#include <ymir/semantic/generator/type/FuncPtr.hh>
#include <ymir/semantic/generator/type/Integer.hh>
#include <ymir/semantic/generator/type/LambdaType.hh>
#include <ymir/semantic/generator/type/NoneType.hh>
#include <ymir/semantic/generator/type/Pointer.hh>
#include <ymir/semantic/generator/type/Slice.hh>
#include <ymir/semantic/generator/type/StructRef.hh>
#include <ymir/semantic/generator/type/EnumRef.hh>
#include <ymir/semantic/generator/type/Range.hh>
#include <ymir/semantic/generator/type/Tuple.hh>
#include <ymir/semantic/generator/type/TraitRef.hh>
#include <ymir/semantic/generator/type/Void.hh>
