#pragma once

#include <ymir/syntax/declaration/Alias.hh>
#include <ymir/syntax/declaration/Block.hh>
#include <ymir/syntax/declaration/Class.hh>
#include <ymir/syntax/declaration/CondBlock.hh>
#include <ymir/syntax/declaration/Constructor.hh>
#include <ymir/syntax/declaration/Enum.hh>
#include <ymir/syntax/declaration/ExpressionWrapper.hh>
#include <ymir/syntax/declaration/ExternBlock.hh>
#include <ymir/syntax/declaration/Function.hh>
#include <ymir/syntax/declaration/Global.hh>
#include <ymir/syntax/declaration/Import.hh>
#include <ymir/syntax/declaration/Macro.hh>
#include <ymir/syntax/declaration/Mixin.hh>
#include <ymir/syntax/declaration/Module.hh>
#include <ymir/syntax/declaration/Struct.hh>
#include <ymir/syntax/declaration/Template.hh>
#include <ymir/syntax/declaration/Trait.hh>
#include <ymir/syntax/declaration/Use.hh>
